### ISSUE TITLE
Memory Leak with cudarc 0.9.0

### ISSUE THREAD

**Issue by jafioti** [coreylowman/dfdx#562] opened 2023-03-13 00:17 UTC
I ran into a new memory leak when upgrading dfdx to a version using cudarc 0.9.0. I have fixed the leak by simply downgrading to cudarc 0.8.0 and replacing the `backward()` function in `src/tensor_ops/utilities/cuda_kernels.rs` with this:
```rust
let bwd_lhs_fn = self
      .dev
      .get_func(K::MODULE_NAME, K::BWD_LHS_FN_NAME)
      .unwrap();

  let bwd_rhs_fn = self
      .dev
      .get_func(K::MODULE_NAME, K::BWD_RHS_FN_NAME)
      .unwrap();

  let numel = lhs.shape.num_elements();

  let ((out_dims1, out_strides1), rhs_strides1) = permute_for_binary_backward(
      lhs.shape.concrete(),
      lhs.shape.strides(),
      rhs.strides,
      lhs.strides,
  );

  let ((out_dims2, out_strides2), lhs_strides2) = permute_for_binary_backward(
      lhs.shape.concrete(),
      lhs.shape.strides(),
      lhs.strides,
      rhs.strides,
  );

  let out_dims1 = self.dev.htod_copy(out_dims1)?;
  let out_strides1 = self.dev.htod_copy(out_strides1)?;
  let rhs_strides1 = self.dev.htod_copy(rhs_strides1)?;
  let out_dims2 = self.dev.htod_copy(out_dims2)?;
  let out_strides2 = self.dev.htod_copy(out_strides2)?;
  let lhs_strides2 = self.dev.htod_copy(lhs_strides2)?;

  let chunk_len1 = numel / physical_numel(lhs.shape.concrete(), lhs.strides);
  let chunk_len2 = numel / physical_numel(rhs.shape.concrete(), rhs.strides);

  let params_lhs = (
      op.clone(),        // const OP_STRUCT op,
      numel,             // const size_t numel,
      S::NUM_DIMS,       // const size_t num_dims,
      &out_dims1,        // const size_t *dims,
      &out_strides1,     // const size_t *out_strides,
      lhs.data.as_ref(), // const TYPENAME *lhs,
      grad_lhs,          // TYPENAME *grad_lhs,
      chunk_len1,        // const size_t chunk_len,
      rhs.data.as_ref(), // const TYPENAME *rhs,
      &rhs_strides1,     // const size_t *rhs_strides,
      grad_out,          // const TYPENAME *grad_out
  );

  let params_rhs = (
      op,                // const OP_STRUCT op,
      numel,             // const size_t numel,
      S::NUM_DIMS,       // const size_t num_dims,
      &out_dims2,        // const size_t *dims,
      &out_strides2,     // const size_t *out_strides,
      lhs.data.as_ref(), // const TYPENAME *lhs,
      &lhs_strides2,     // const size_t *lhs_strides,
      rhs.data.as_ref(), // const TYPENAME *rhs,
      grad_rhs,          // TYPENAME *grad_rhs,
      chunk_len2,        // const size_t chunk_len,
      grad_out,          // const TYPENAME *grad_out
  );

  let cfg = LaunchConfig::for_num_elems(numel as u32);
  let stream = self.dev.fork_default_stream()?;

  unsafe { bwd_lhs_fn.launch(cfg, params_lhs) }?;
  unsafe { bwd_rhs_fn.launch_on_stream(&stream, cfg, params_rhs) }?;
  Ok(())
```
This is what was in the function before 0.9.0, so I don't know if the leak resides in here or somewhere else in cudarc. I only changed this function because the cudarc api changed so I had to.

Everything else in dfdx stayed the same, and the leak disappeared.

**Comment by coreylowman** [comment] 2023-03-13 15:54
@jafioti can you share a nsight report for this? those are super useful

**Comment by coreylowman** [comment] 2023-03-13 19:18
Yeah I think I need more details to actually try to reproduce.

**Comment by coreylowman** [comment] 2023-03-13 19:40
The relevant change from 0.8 to 0.9 is that i moved the memory free back to the default thread instead of a separate thread. I suspect the memory leak will happen in either case.

I noticed you're using `.traced()` (https://github.com/jafioti/lm_test/blob/main/src/main.rs#L164), which I suspect is the culprit. Can you try the following diff?

```rust
let grads = gradients.unwrap_or_else(|| model.alloc_grads());
let input = dev
    .tensor_from_vec(flat_vec, (batch_size, seq_len))
    .trace_into(g);
```

Tagging #565 since I think its relevant.

**Comment by jafioti** [comment] 2023-03-13 20:52
Ok will do. I don't think the traced() actually gets called unless a previous loop had an error though,  so I don't think its the culprit.

**Comment by coreylowman** [comment] 2023-03-21 14:34
@jafioti any more info you can share? Will close this out if not since I've been unable to reproduce

**Comment by jafioti** [comment] 2023-03-21 14:40
@coreylowman Sorry haven't had a chance to create a repro, will try to tonight.

**Comment by coreylowman** [comment] 2023-03-25 15:00
Closing for now - feel free to reopen with more details

**Closed by coreylowman** 2023-03-25 15:00 UTC
